[build]
  command = "nvm install 18 && npm install --legacy-peer-deps && gatsby build"
  publish = "public"
  functions = "functions"  # Adjust if you have serverless functions
  
  [build.cache]
    paths = [
      ".cache/**",
      "node_modules/**"
      # Add other directories you want to cache during builds, if any
    ]

# Optional settings for headers, redirects, etc.
[build.environment]
  # Example: Setting environment variables during build
  NODE_VERSION = "18"

[[plugins]]
  package = "@netlify/plugin-gatsby"
