[build]
  command = "npm install --legacy-peer-deps && gatsby build"
  publish = "public"
  functions = "functions"  # Adjust if you have serverless functions
  # Cache settings for Gatsby and Netlify build artifacts
  cache = {
    # Caching node modules and Gatsby cache
    paths = [
      ".cache/**",
      "node_modules/**",
      # Add other directories you want to cache during builds, if any
    ]
  }

# Optional settings for headers, redirects, etc.
[build.environment]
  # Example: Setting environment variables during build
  NODE_VERSION = "14"

[[plugins]]
  package = "@netlify/plugin-gatsby"
